ie:
  build: .
  ports:
    - "3001:3001"
  links:
    - mongodb:mongo
    - riskservice:riskservice
endpoint:
  build: ../ie-ccda-endpoint
  ports:
    - "3000:3000"
  links:
    - ie
mongodb:
  image: mongo
  volumes:
    - /data/db:/data/db
  ports:
    - "27017:27017"
riskservice:
  build: ../multifactorriskservice
  ports:
    - "9000:9000"
  links:
    - mongodb:mongo
  command: /bin/bash -c "/go/src/github.com/intervention-engine/multifactorriskservice/multifactorriskservice -redcap http://redcapsrv.org -token abcdefg -fhir '$$IE_PORT_3001_TCP_ADDR:$$IE_PORT_3001_TCP_PORT' -cron 0 0 22 * * *"
nginx:
  build: ../nginx
  ports:
    - "8080:8080"
    - "443:443"
  links:
    - ie
  command: /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf '$$IE_PORT_3001_TCP_ADDR:$$IE_PORT_3001_TCP_PORT' && nginx -g 'daemon off;'"
